### ISSUE TITLE
Description of the `./specimen.png`

### ISSUE THREAD

**Issue by pathumego** [djrrb/Sample-Font-Repository#1]
README is missing an explanation to `./specimen.png` :) 

I know, it's self explanatory, but I am trying to address https://github.com/raphaelbastide/Unified-Font-Repository/issues/23 and clarifying this would help. Thanks for sharing this!

**Comment by djrrb** [comment]
@pathumego Thanks for checking this out and for your efforts on the Unified Font Repository. I added a brief description, and let me know if there’s anything else I can do.
