### ISSUE TITLE
README contents license

### ISSUE THREAD

**Issue by pathumego** [djrrb/Sample-Font-Repository#2]
@djrrb Could we use bits from your description of the repository on README.md to update [ABOUT.en_us.md](https://github.com/unified-font-repository/Unified-Font-Repository/blob/master/ABOUT.en_us.md) on UFR repo?

**Comment by pathumego** [comment]
@djrrb ping :)

**Comment by djrrb** [comment]
Sorry thought I responded to this. Yes, go ahead!

**Comment by pathumego** [comment]
Thanks!
